alias gti="git"
alias npmisd="npm install --save-dev"
alias npmis="npm install --save"
alias killdebug="lsof -i TCP -n | grep 5858 | awk '{print $2}' | xargs kill"
alias node-debug="node-debug --web-port=8088"
